engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
ratings:
  paths:
    - "src/**/*"
exclude_paths:
    - vendor/**/*
    - tests/**/*
    - src/drivers/payonline/PayOnline.php
    - src/drivers/tinkoff/TinkoffMerchantAPI.php